{% set name = "pgure-svt" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tjof2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 65158ca6b46bd3b4cf96123b513d1348df18c0277f5cc6946b227149a8b28401
  patches:
    - march.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - armadillo
    - cython
    - liblapack
    - nlopt
    - numpy
    - openblas
    - pip
    - python
  run:
    - armadillo
    - liblapack
    - nlopt
    - {{ pin_compatible('numpy') }}
    - openblas
    - python

test:
  requires:
    - hyperspy-base
  imports:
    - pguresvt.svt
    - pguresvt.hspysvt

about:
  home: https://github.com/tjof2/pgure-svt
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Singular value thresholding for denoising time-resolved microscopy'
  description: |
    PGURE-SVT (Poisson-Gaussian Unbiased Risk Estimator - Singular Value Thresholding) is an algorithm designed to denoise image sequences acquired in microscopy. It exploits the correlations between consecutive frames to form low-rank matrices, which are then recovered using a technique known as nuclear norm minimization. An unbiased risk estimator for mixed Poisson-Gaussian noise is used to automate the selection of the regularization parameter, while robust noise and motion estimation maintain broad applicability to many different types of microscopy.
  doc_url: https://github.com/tjof2/pgure-svt
  dev_url: https://github.com/tjof2/pgure-svt

extra:
  recipe-maintainers:
    - ericpre
    - tjof2
